[package]
name = "jitexpr"
version = "0.1.0"
edition = "2024"
license = "MIT"
homepage = "https://github.com/quickwit-oss/tantivy"
repository = "https://github.com/quickwit-oss/tantivy"
description = "JIT-compiled expression evaluation for tantivy"

[dependencies]
cranelift = "0.134.3"
cranelift-jit = "0.136.0"
cranelift-module = "0.134.3"
cranelift-native = "0.134.3"
lru = "0.18.2"
regex = "1"
thiserror = "2.0.1"
